= Retailer example application


== Application architecture

This application has a microservice architecture. It is made up of Catalog
subdomain and Order subdomain. Each subdomain has one to one mapping to
a bounded context in the solution space.

Each bounded context adheres to a Domain-driven Design architecture. Bounded
contexts have 100% asynchronous communication patterns. The infrastructure
that underlies is a set of building blocks from the Eventuate framework:
MySql as a transtional event storage, a process implementing Change Data
Capture (CDC) to relay the Aggregate events to Kafka, kafka as a message
broker (zookeper is needed).

There are the following services:

* link:./catalog-service[catalog-service] - the `Catalog Service`
* link:./catalog-view-service[catalog-view-service] - the `Catalog View Service`
* link:./order-service[order-service] - the `Order Service`

== Service design

Key points:

* A service consists of a single Gradle module.
* A service is a Spring Boot application.
* A service has a Swagger UI `http://.../swagger-ui.html`. See `show-swagger-urls.sh`
* A service typically consists of the following packages:
** backend.domain - domain logic including aggregates
** backend.handlers - messaging handlers
** backend.service -  use case scenarios
** backend.repository -  CQRS views materialization
** web - Spring MVC controllers

* The services use the following framework for event sourcing support:
** https://github.com/eventuate-clients/eventuate-client-java[`Eventuate Client framework`] - implements event sourcing

== Building and running the application

=== Pre-requisites

* Java 8
* Docker and Docker Compose
* Internet access so that Gradle and Docker can download dependencies and container images


=== Setting environment variables

To run the application you must set the `DOCKER_HOST_IP` environment variable to
 the IP address of where the Docker containers are running.

On Linux you might get some help with:

```
hostname -I
```

or

```
ifconfig
```

Do NOT set it to the (unresolvable) hostname of your machine,
`localhost` or `127.0.0.1`.


=== Building and Testing

```
DOCKER_HOST_IP=<IP> ./_build-and-test-all.sh
```

=== Building and Running

```
DOCKER_HOST_IP=<IP> ./build-and-run.sh
```

=== Stopping the application

Stop the application using this command:

```
./stop-and-rm.sh
```

=== Using the application

Use the services Swagger UIs to invoke the services.

* Create Catalog Entry - `http://${DOCKER_HOST_IP?}:8081/swagger-ui.html`
* View the Catalog Entry Query Side - `http://${DOCKER_HOST_IP?}:8082/swagger-ui.html`
* Create an order - `http://${DOCKER_HOST_IP?}:8083/swagger-ui.html`

To get  better grasp of the application, the end-to-end test runs a
comprehensive scenario:

* Phone entry created on Catalog command side.
* Order created on Order command side.
* Phone entry modified on Catalog command side.
* Order created on Order command side with the modified phone.
* Phone entry deleted.
* Attempt to create an Order with a non-existent Phone record (422 Error).
